config/routes.rb
Rails.application.routes.draw do
  match "(*any)",
    to: redirect(subdomain: ""),
    via: :all,
    constraints: { subdomain: "www" } unless Rails.env.test?\

  root 'home#index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get '/about' => 'home#about', as: 'about'
  get '/questions' => 'home#questions', as: 'questions'
  get '/search' => 'reservations#search', as: 'reservation_lookup'
  post '/search' => 'reservations#search'

  get '/donation' => 'donations#donation_without_reservation', as: 'donation_without_reservation'
  get '/thank-you-for-your-donation' => 'donations#success', as: 'success'

  get '/software' => 'home#software', as: 'software'

  post 'messages/reply' => 'messages#reply'

  get '/tree-program', to: redirect('/about') # this redirect old web links to this site

  get '/sitemap.xml', to: 'sitemap#index', as: 'sitemap', :defaults => {:format => 'xml'}

  resources :reservations, except: [:index] do
    get 'address-verification', as: 'address_verification'

    resources :donations, only: %i[ new create ]
    post 'cash-or-check' => 'donations#cash_or_check', as: 'cash_or_check'
    post 'no-donation' => 'donations#no_donation', as: 'no_donation'
    get 'donations/success' => 'donations#success', as: 'success'
    get 'donations/cancel' => 'donations#cancel', as: 'cancel'
    get 'confirmed' => 'reservations#confirmed', as: 'confirmed'


    post 'submit-reservation' => 'reservations#submit_confirmed_reservation', as: 'submit'
    get 'unsubscribe' => 'reservations#unsubscribe', as: 'unsubscribe'
    get 'resubscribe' => 'reservations#resubscribe', as: 'resubscribe'
  end

  post 'stripe-webhook' => "donations#stripe_webhook"

  namespace :driver do
    root 'zones#index'
    get 'instructions' => 'routes#instructions', as: 'instructions'
    get 'contact' => 'contact#index', as: 'contacts'
    get 'reservations/map' => 'reservations#map', as: 'reservations_map'
    get 'search' => 'reservations#search', as: 'search'
    resources :reservations, only: %i( update show ) do
      get 'map' => 'reservations#map', as: 'map'
    end
    resources :routes, only: %i( show index )
    resources :drivers, only: %i( index show )
    get '/routing' => 'zones#index', as: 'routing'
    get '/zones' => 'zones#index', as: 'zones'
  end

  namespace :admin do
    root 'admin#index'
    get 'operations/index' => 'operations#index', as: 'operations'
    patch 'operations/update'
    get '/routes/map-all' => 'routes#map_all', as: 'routes_map_all'
    resources :zones
    resources :drivers
    get 'logs' => 'logs#index', as: :logs
    resources :messages, only: [:index, :create, :destroy ]
    resources :marketing, only: [ :index ]

    resources :settings, only: [ :index, :edit, :update ]


    resources :users, only: [ :index, :update, :create, :destroy, :edit ]
    resources :driver_routes, only: [:create, :destroy]
    resources :points, only: [:create, :update, :destroy, :edit]
    delete 'reservations/archive-all' => 'reservations#post_event_archive', as: 'post_event_archive_reservations'
    delete 'reservations/destroy-all' => 'reservations#destroy_all', as: 'destroy_all_reservations'
    delete 'donations/destroy-all' => 'donations#destroy_all', as: 'destroy_all_donations'
    delete 'reservations/destroy-all-archived' => 'reservations#destroy_all_archived', as: 'destroy_all_archived_reservations'
    delete 'reservations/destroy-unconfirmed' => 'reservations#destroy_unconfirmed', as: 'destroy_unconfirmed_reservations'
    post 'reservations/destroy-reservations' => 'reservations#destroy_reservations', as: 'destroy_reservations'
    delete 'reservations/destroy-logs' => 'logs#destroy', as: 'destroy_all_logs'
    resources :donations do
      post 'send-donation-receipt' => 'donations#send_donation_receipt', as: 'send_donation_receipt'
    end
    resources :reservations, only: [ :index, :show, :edit, :update, :destroy, :archive ] do
      resources :donations
      get 'logs' => 'logs#reservation_index', as: 'logs'
      post 'process-route' => 'reservations#process_route', as: 'process_route'
      post 'process-geocode' => 'reservations#process_geocode', as: 'process_geocode'
      post 'archive' => 'reservations#archive', as: 'archive'
    end
    get '/routing' => 'zones#index', as: 'routing'
    get '/phone' => 'messages#show', as: 'phone'

    post '/marketing/send-email-1' => 'marketing#send_marketing_email_1', as: 'marketing_send_email_1'
    post '/marketing/send-email-2' => 'marketing#send_marketing_email_2', as: 'marketing_send_email_2'
    post '/send-pickup-reminders' => 'reservations#send_pickup_reminders', as: 'send_pickup_reminders'
    post '/marketing/reset-sent-campaigns' => 'marketing#reset_sent_campaigns', as: 'marketing_reset_sent_campaigns'
    get '/analytics' => 'analytics#index', as: 'analytics'

    post 'process-all-routes' => 'reservations#process_all_routes', as: 'process_all_routes'
    get 'map' => 'reservations#map', as: 'map'
    resources :routes, except: [ :index, :show ] do
      get 'map' => 'routes#map', as: 'map'
    end
    get 'search' => 'reservations#search', as: 'search'
    post 'res-upload' => 'reservations#upload', as: 'upload'
  end


  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match "/422", to: "errors#unprocessable_entity", via: :all
end

app/views/shared/_admin_header.haml
%header.mb-lg-5
  %nav.navbar.navbar-expand-lg.navbar-dark#admin-navbar
    .container-fluid
      - site_title = 'Admin'

      = link_to admin_root_path, class: 'navbar-brand' do
        %i.bi.bi-tree-fill
        = site_title

      %button.navbar-toggler(type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation")
        %span.navbar-toggler-icon
      .collapse.navbar-collapse#navbarSupportedContent
        %ul.navbar-nav.me-auto.mb-2.mb-lg-0


          - if signed_in?

            %li.nav-item
              = link_to "Reservations", admin_reservations_path, class: "nav-link #{ controller_name == 'reservations' ? 'active' : nil }"
            %li.nav-item
              = link_to "Routes", admin_routing_path, class: "nav-link #{ controller_name == 'zones' ? 'active' : nil }"
            %li.nav-item
              = link_to "Donations", admin_donations_path, class: "nav-link #{ controller_name == 'donations' ? 'active' : nil }"
            %li.nav-item.message
              = link_to admin_messages_path, class: "nav-link #{ controller_name == 'messages' ? 'active' : nil }" do
                Messages
              = turbo_stream_from "messages-count"
              = render 'admin/messages/count'
            %li.nav-item
              = link_to "Analytics", admin_analytics_path, class: "nav-link #{ controller_name == 'analytics' ? 'active' : nil }"
            %li.nav-item
              = link_to "Marketing", admin_marketing_index_path, class: "nav-link #{ controller_name == 'marketing' ? 'active' : nil }"
            %li.nav-item
              = link_to admin_settings_path, class: "nav-link #{ controller_name == 'settings' ? 'active' : nil }", id: 'settings-link' do
                %i.bi.bi-gear-fill
        %ul.navbar-nav.my-2.my-lg-0
          %li.nav-item
            = link_to "Make a Reservation", root_path, class: 'btn btn-outline-light btn-site'
          %li.nav-item
            = link_to "Driver", driver_root_path, class: 'btn btn-outline-light btn-site'
          %li.nav-item
            - if signed_in?
              %li.nav-item= button_to 'Sign out', sign_out_path, method: :delete, class: 'btn btn-primary'
            - else
              %li.nav-item= link_to 'Sign in', sign_in_path, class: "nav-link #{}"

app/views/shared/_driver_header.html.haml
%header.mb-lg-5
  %nav.navbar.navbar-expand.navbar-dark#driver-navbar
    .container
      = link_to driver_root_path, class: 'navbar-brand' do
        %i.bi.bi-truck-front-fill
        = DRIVER_SITE_TITLE


      %ul.navbar-nav
        / %li.nav-item
        /   = link_to "Main", root_path, class: 'btn btn-outline-light btn-site'
        - if signed_in?
          %li.nav-item
            = link_to "Admin", admin_root_path, class: "btn btn-outline-light btn-site"


  %ul.nav.justify-content-center#driver-nav
    %li.nav-item
      = link_to driver_zones_path, class: 'nav-link' do
        %i.bi.bi-signpost-2-fill
        Routes
    %li.nav-item
      = link_to donation_without_reservation_path(driver: true), local: true, data: { turbo:false }, class: 'nav-link' do
        %i.bi.bi-credit-card-fill
        Donation

    %li.nav-item
      = link_to driver_contacts_path, class: 'nav-link' do
        %i.bi.bi-telephone-fill
        Contact
    %li.nav-item
      = link_to driver_search_path, class: 'nav-link' do
        %i.bi.bi-search
        Search

app/views/shared/_flash.html.haml
- if flash.present?
  .container.d-print-none
    #flash
      - flash.each do |key, value|
        .alert{class: key == 'notice' ? 'alert-primary' : 'alert-warning'}
          = value.html_safe if value.present?

app/views/shared/_footer.html.haml
%footer.d-none.d-sm-block
  .container

app/views/shared/_head.html.haml
%head
  %title
    - if @site_title
      = @site_title
      \-
    - if driver_view?
      = DRIVER_SITE_TITLE
      \-
    - elsif admin_view?
      = ADMIN_SITE_TITLE
      \-
    = SITE_TITLE
  %meta(name="viewport" content="width=device-width,initial-scale=1")
  - if setting.meta_description
    %meta{ name: "description", content: setting.meta_description }
  = csrf_meta_tags
  = csp_meta_tag

  - if driver_view? || admin_view? || controller_name == 'sessions'
    %meta(name="robots" content="noindex")

  %link{ rel:"canonical", href: "https://treerecycle.net" + request.path }

  <!-- Facebook meta -->
  - if setting.facebook_page_id.present?
    %meta{ property: 'fb:admins', content: setting.facebook_page_id } 
  - if setting.meta_site_name.present?
    %meta{ property: 'og:site_name', content: setting.meta_site_name }
  - if setting.meta_description.present?
    %meta{ property: 'og:description', content: setting.meta_description }
  - if setting.meta_image_filename.present?
    %meta{ property: 'og:image', content: "#{ image_url(setting.meta_image_filename) }" }


  <!-- CSS only -->
  - if driver_view?
    = favicon_link_tag 'driver/apple-touch-icon-57x57.png', rel: 'apple-touch-icon', sizes: '57x57', type: 'image/png'
    = favicon_link_tag 'driver/apple-touch-icon-76x76.png', rel: 'apple-touch-icon', sizes: '76x76', type: 'image/png'
    = favicon_link_tag 'driver/apple-touch-icon-72x72.png', rel: 'apple-touch-icon', sizes: '72x72', type: 'image/png'
    = favicon_link_tag 'driver/apple-touch-icon-114x114.png', rel: 'apple-touch-icon', sizes: '114x114', type: 'image/png'
    = favicon_link_tag 'driver/apple-touch-icon-120x120.png', rel: 'apple-touch-icon', sizes: '120x120', type: 'image/png'
    = favicon_link_tag 'driver/apple-touch-icon-144x144.png', rel: 'apple-touch-icon', sizes: '144x144', type: 'image/png'
    = favicon_link_tag 'driver/apple-touch-icon-152x152.png', rel: 'apple-touch-icon', sizes: '152x152', type: 'image/png'
    = favicon_link_tag 'driver/apple-touch-icon-180x180.png', rel: 'apple-touch-icon', sizes: '180x180', type: 'image/png'
    = favicon_link_tag 'driver/apple-touch-icon.png', rel: 'shortcut icon',type: 'image/x-icon'
    = favicon_link_tag 'driver/apple-touch-icon.png', rel: 'apple-touch-icon'
  - else
    = favicon_link_tag 'apple-touch-icon-57x57.png', rel: 'apple-touch-icon', sizes: '57x57', type: 'image/png'
    = favicon_link_tag 'apple-touch-icon-76x76.png', rel: 'apple-touch-icon', sizes: '76x76', type: 'image/png'
    = favicon_link_tag 'apple-touch-icon-72x72.png', rel: 'apple-touch-icon', sizes: '72x72', type: 'image/png'
    = favicon_link_tag 'apple-touch-icon-114x114.png', rel: 'apple-touch-icon', sizes: '114x114', type: 'image/png'
    = favicon_link_tag 'apple-touch-icon-120x120.png', rel: 'apple-touch-icon', sizes: '120x120', type: 'image/png'
    = favicon_link_tag 'apple-touch-icon-144x144.png', rel: 'apple-touch-icon', sizes: '144x144', type: 'image/png'
    = favicon_link_tag 'apple-touch-icon-152x152.png', rel: 'apple-touch-icon', sizes: '152x152', type: 'image/png'
    = favicon_link_tag 'apple-touch-icon-180x180.png', rel: 'apple-touch-icon', sizes: '180x180', type: 'image/png'
    = favicon_link_tag 'apple-touch-icon.png', rel: 'shortcut icon',type: 'image/x-icon'
    = favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon'

  %link(href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous")
  %script(src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous")
  = stylesheet_link_tag "application", "data-turbo-track": "reload"
  = javascript_importmap_tags

app/views/shared/_header.html.haml
%header.mb-lg-5
  %nav.navbar.navbar-expand-lg.navbar-dark#main-navbar
    .container
      = link_to root_url, class: 'navbar-brand' do
        %i.bi.bi-tree-fill
        = SITE_TITLE

      %button.navbar-toggler(type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation")
        %span.navbar-toggler-icon
      .collapse.navbar-collapse#navbarSupportedContent
        %ul.navbar-nav.me-auto.mb-2.mb-lg-0
          %li.nav-item
            = link_to "New reservation", new_reservation_url, class: "nav-link #{ controller_name == 'reservations' && action_name == 'new' ? 'active' : nil }", "aria-current": "page"
          %li.nav-item
            = link_to "Donate", donation_without_reservation_path, local: true, data: { turbo:false } , class: "nav-link #{ controller_name == 'donations' ? 'active' : nil }", "aria-current": "page"
          - if setting.is_reservations_open? && RESERVATION_LOOKUP_ENABLED == true
            %li.nav-item
              = link_to reservation_lookup_url, class: "nav-link #{ action_name == 'lookup' ? 'active' : nil }", "aria-current": "page", id: 'reservation_lookup_link' do
                Reservation Lookup
          %li.nav-item
            = link_to questions_url, class: "nav-link #{ controller_name == 'home' && action_name == 'questions' ? 'active' : nil }", "aria-current": "page", id: 'question_header_link' do
              Questions?
          %li.nav-item
            = link_to "About", about_url, class: "nav-link #{ controller_name == 'home' && action_name == 'about' ? 'active' : nil }"

        - if signed_in?
          %ul.navbar-nav.my-2.my-lg-0#admin-nav-links
            %li.nav-item
              = link_to "Admin", admin_root_path, class: "btn btn-outline-light btn-site"
            %li.nav-item
              = link_to "Driver", driver_root_path, class: 'btn btn-outline-light btn-site'
            %li.nav-item= button_to 'Sign out', sign_out_path, method: :delete, class: 'btn btn-primary'

app/views/shared/_mailer_footer.haml
%p(style="font-family:'SF UI Display Medium',system,-apple-system,-webkit-system-font,'SFNSText','Segoe UI','Helvetica Neue',Helvetica,Arial,sans-serif !important; box-sizing: border-box; line-height: 1.5; font-weight:400; font-size: 13px; font-weight: normal; margin: 0 0 25px; padding: 0;")
  = MAIL_FOOTER

app/views/shared/_map_js.html.erb
// Create the map, centered at gfg_office
var map = new google.maps.Map(
        document.getElementById("map"), {

    // Set the zoom of the map
    <%- if @route %>
      zoom: 15,
      center: new google.maps.LatLng(<%= @route.latitude %>, <%= @route.longitude %>),
    <%- elsif @reservation %>
      zoom: 19,
      center: new google.maps.LatLng(<%= @reservation.latitude %>, <%= @reservation.longitude %>),
    <%- elsif @zone %>
      zoom: 13,
      center: new google.maps.LatLng(<%= @zone.latitude %>, <%= @zone.longitude %>),
    <%- else %>
      zoom: 12,
      center: new google.maps.LatLng(47.64483,-122.54827),
    <%- end %>
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    mapId: "4504f8b37365c3d0"
});

app/views/shared/_pin_colors_js.html.erb
const pinViewBackgroundPickedUp = new google.maps.marker.PinView({
  background: "#efefef",
  scale: 0.7,
});

const pinViewBackgroundPending = new google.maps.marker.PinView({
  background: "#003F87",
  glyphColor: "white"
});

const pinViewBackgroundMissing = new google.maps.marker.PinView({
  background: "#CE1126",
  glyphColor: "white"
});

const pinViewBackgroundArchived = new google.maps.marker.PinView({
  background: "#aaaaaa",
  glyphColor: "#000000"
});

app/views/shared/_side_info.html.haml
- if @reservation
  #side-info
    %h1 Summary

    - if @reservation.name
      .section.name
        %h2 Name
        .full_name= @reservation.name


    - if @reservation.street
      .section.address
        %h2 Address

        - if @reservation.street
          .street= @reservation.street
        .city= @reservation.city
        .state= @reservation.state

        - if @reservation.notes.present?
          %br
          .notes= @reservation.notes

    .section.pickup-details
      %h2 Pickup details
      %h3 Date
      #pickup-date= nice_date(Time.parse(EVENT_DATE_AND_PICKUP_TIME))

      %h3 Pickup-time
      #pickup-time
        = nice_time(Time.parse(EVENT_DATE_AND_PICKUP_TIME))
        \-
        = nice_time(Time.parse(EVENT_DATE_AND_PICKUP_END_TIME))

    - if @reservation.email
      .section.contact-info
        %h2 Contact
        .email= @reservation.email
        - if @reservation.phone.present?
          %br
          .phone= @reservation.phone

    = render 'reservations/reservation_actions'

    - if @reservation.persisted?
      %p= link_to 'Donate', new_reservation_donation_path(@reservation)