config/routes.rb
Rails.application.routes.draw do
  match "(*any)",
    to: redirect(subdomain: ""),
    via: :all,
    constraints: { subdomain: "www" } unless Rails.env.test?\

  root 'home#index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get '/about' => 'home#about', as: 'about'
  get '/questions' => 'home#questions', as: 'questions'
  get '/search' => 'reservations#search', as: 'reservation_lookup'
  post '/search' => 'reservations#search'

  get '/donation' => 'donations#donation_without_reservation', as: 'donation_without_reservation'
  get '/thank-you-for-your-donation' => 'donations#success', as: 'success'

  get '/software' => 'home#software', as: 'software'

  post 'messages/reply' => 'messages#reply'

  get '/tree-program', to: redirect('/about') # this redirect old web links to this site

  get '/sitemap.xml', to: 'sitemap#index', as: 'sitemap', :defaults => {:format => 'xml'}

  resources :reservations, except: [:index] do
    get 'address-verification', as: 'address_verification'

    resources :donations, only: %i[ new create ]
    post 'cash-or-check' => 'donations#cash_or_check', as: 'cash_or_check'
    post 'no-donation' => 'donations#no_donation', as: 'no_donation'
    get 'donations/success' => 'donations#success', as: 'success'
    get 'donations/cancel' => 'donations#cancel', as: 'cancel'
    get 'confirmed' => 'reservations#confirmed', as: 'confirmed'


    post 'submit-reservation' => 'reservations#submit_confirmed_reservation', as: 'submit'
    get 'unsubscribe' => 'reservations#unsubscribe', as: 'unsubscribe'
    get 'resubscribe' => 'reservations#resubscribe', as: 'resubscribe'
  end

  post 'stripe-webhook' => "donations#stripe_webhook"

  namespace :driver do
    root 'zones#index'
    get 'instructions' => 'routes#instructions', as: 'instructions'
    get 'contact' => 'contact#index', as: 'contacts'
    get 'reservations/map' => 'reservations#map', as: 'reservations_map'
    get 'search' => 'reservations#search', as: 'search'
    resources :reservations, only: %i( update show ) do
      get 'map' => 'reservations#map', as: 'map'
    end
    resources :routes, only: %i( show index )
    resources :drivers, only: %i( index show )
    get '/routing' => 'zones#index', as: 'routing'
    get '/zones' => 'zones#index', as: 'zones'
  end

  namespace :admin do
    root 'admin#index'
    get 'operations/index' => 'operations#index', as: 'operations'
    patch 'operations/update'
    get '/routes/map-all' => 'routes#map_all', as: 'routes_map_all'
    resources :zones
    resources :drivers
    get 'logs' => 'logs#index', as: :logs
    resources :messages, only: [:index, :create, :destroy ]
    resources :marketing, only: [ :index ]

    resources :settings, only: [ :index, :edit, :update ]


    resources :users, only: [ :index, :update, :create, :destroy, :edit ]
    resources :driver_routes, only: [:create, :destroy]
    resources :points, only: [:create, :update, :destroy, :edit]
    delete 'reservations/archive-all' => 'reservations#post_event_archive', as: 'post_event_archive_reservations'
    delete 'reservations/destroy-all' => 'reservations#destroy_all', as: 'destroy_all_reservations'
    delete 'donations/destroy-all' => 'donations#destroy_all', as: 'destroy_all_donations'
    delete 'reservations/destroy-all-archived' => 'reservations#destroy_all_archived', as: 'destroy_all_archived_reservations'
    delete 'reservations/destroy-unconfirmed' => 'reservations#destroy_unconfirmed', as: 'destroy_unconfirmed_reservations'
    post 'reservations/destroy-reservations' => 'reservations#destroy_reservations', as: 'destroy_reservations'
    delete 'reservations/destroy-logs' => 'logs#destroy', as: 'destroy_all_logs'
    resources :donations do
      post 'send-donation-receipt' => 'donations#send_donation_receipt', as: 'send_donation_receipt'
    end
    resources :reservations, only: [ :index, :show, :edit, :update, :destroy, :archive ] do
      resources :donations
      get 'logs' => 'logs#reservation_index', as: 'logs'
      post 'process-route' => 'reservations#process_route', as: 'process_route'
      post 'process-geocode' => 'reservations#process_geocode', as: 'process_geocode'
      post 'archive' => 'reservations#archive', as: 'archive'
    end
    get '/routing' => 'zones#index', as: 'routing'
    get '/phone' => 'messages#show', as: 'phone'

    post '/marketing/send-email-1' => 'marketing#send_marketing_email_1', as: 'marketing_send_email_1'
    post '/marketing/send-email-2' => 'marketing#send_marketing_email_2', as: 'marketing_send_email_2'
    post '/send-pickup-reminders' => 'reservations#send_pickup_reminders', as: 'send_pickup_reminders'
    post '/marketing/reset-sent-campaigns' => 'marketing#reset_sent_campaigns', as: 'marketing_reset_sent_campaigns'
    get '/analytics' => 'analytics#index', as: 'analytics'

    post 'process-all-routes' => 'reservations#process_all_routes', as: 'process_all_routes'
    get 'map' => 'reservations#map', as: 'map'
    resources :routes, except: [ :index, :show ] do
      get 'map' => 'routes#map', as: 'map'
    end
    get 'search' => 'reservations#search', as: 'search'
    post 'res-upload' => 'reservations#upload', as: 'upload'
  end


  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match "/422", to: "errors#unprocessable_entity", via: :all
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :reservation, optional: true
  validates :form, presence: true

  after_update :send_receipt_email!, if: -> (obj){ obj.amount.positive? && obj.email.present? && !obj.saved_change_to_is_receipt_email_sent? }

  enum :form, { online: 1, cash_or_check: 2 }, default: 1

  scope :current_event, -> { where("created_at > ?", Date.today - 6.months)}

  def send_receipt_email!
    return if self.is_receipt_email_sent?
    DonationsMailer.with(donation: self).receipt_email.deliver_later
  end
end

app/controllers/admin/donations_controller.rb
class Admin::DonationsController < Admin::AdminController
  def index
    if params[:no_reservation]
      @pagy, @donations = pagy(Donation.where(reservation_id: nil).order(id: :desc))
    else
      @pagy, @donations = pagy(Donation.order(id: :desc))
    end
  end

  def show
    @donation = Donation.find(params[:id])
  end

  def edit
    @donation = Donation.find(params[:id])
  end

  def new
    @reservation = Reservation.find(params[:reservation_id]) if params[:reservation_id]
    @donation = Donation.new
    @donation.form = "cash_or_check"
  end

  def update
    @donation = Donation.find(params[:id])
    if current_user.editor? || current_user.administrator?
      if current_user.editor? || current_user.administrator?
        if @donation.update(donation_params)
          redirect_to admin_donation_url(@donation), notice: "Donation was successfully updated."
        else
          render :edit, status: :unprocessable_entity
        end
      else
        redirect_to admin_donation_url(donation), alert: 'Unauthorized. Editor or Administrator access is required', status: :unauthorized
      end
    else
      render :show, status: :unauthorized
    end
  end

  def create
    if current_user.editor? || current_user.administrator?
      @donation = Donation.new(donation_params)
      @donation.payment_status = 'paid'

      if current_user.editor? || current_user.administrator?
        if @donation.save
          if @donation.reservation_id.present?
            redirect_to admin_reservation_url(@donation.reservation_id)
          else
            redirect_to admin_donations_path
          end
        else
          render :new, status: :unprocessable_entity
        end
      else
        redirect_to admin_donations_url, alert: 'Unauthorized. Editor or Administrator access is required', status: :unauthorized
      end
    else
      @donation = Donation.new
      render :new, status: :unauthorized
    end
  end

  def destroy
    if current_user.editor? || current_user.administrator?
      @donation = Donation.find(params[:id])
      @donation.destroy
      respond_to do |format|
        format.html { redirect_to admin_donations_url, notice: "Donation was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      render :show, status: :unauthorized
    end
  end

  def destroy_all
    if current_user.administrator?
      Donation.destroy_all
      redirect_to admin_operations_path, notice: 'All Donations destroyed'
    else
      redirect_to admin_operations_path, alert: 'Unauthorized. Adminstrator access is required.', status: :unauthorized
    end
  end

  def send_donation_receipt
    donation = Donation.find(params[:donation_id])
    donation.update(is_receipt_email_sent: false)
    donation.send_receipt_email!
    redirect_to admin_reservation_url(donation.reservation)
  end

  private

    def donation_params
      params.require(:donation).permit(:email, :amount, :form, :reservation_id, :note)
    end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  skip_before_action :verify_authenticity_token

  before_action :set_reservation, only: %i[ create new cash_or_check no_donation ]

  def new
  end

  def create
    @reservation.online_donation!
    @session = Stripe::Checkout::Session.create({
      line_items: [{
          price: Rails.env.production? ? STRIPE_PRODUCTION_PRICE_ITEM : STRIPE_DEVELOPMENT_PRICE_ITEM,
          quantity: 1
      }],
      mode: 'payment',
      client_reference_id: @reservation.id,
      metadata: {reservation_id: @reservation.id},
      customer_email: @reservation.email,
      success_url: reservation_success_url(@reservation),
      cancel_url: new_reservation_donation_url(@reservation)
    })
    redirect_to @session.url, allow_other_host: true
  end

  def donation_without_reservation
    @session = Stripe::Checkout::Session.create({
      line_items: [{
          price: Rails.env.production? ? STRIPE_PRODUCTION_PRICE_ITEM : STRIPE_DEVELOPMENT_PRICE_ITEM,
          quantity: 1
      }],
      mode: 'payment',
      success_url: success_url(driver: params[:driver] == 'true' ? true : false),
      cancel_url: params[:driver] && params[:driver] == 'true' ? driver_root_url : root_url
    })
    redirect_to @session.url, allow_other_host: true
  end

  def cash_or_check
    @reservation.cash_or_check_donation!
    @reservation.logs.create(message: 'Cash or check donation option selected.')
    redirect_to reservation_confirmed_url(@reservation), notice: "Your tree pick-up is confirmed. You can leave your donation with your tree."
  end

  def no_donation
    @reservation.no_donation!
    @reservation.logs.create(message: 'No donation option selected.')
    redirect_to reservation_confirmed_url(@reservation)
  end

  def stripe_webhook
    event = Stripe::Event.retrieve(params[:id])
    StripeCharge.new(event).process
    render nothing: true, status: 201
  rescue Stripe::APIConnectionError, Stripe::StripeError
    render nothing: true, status: 400
  end

  def success
    if params[:reservation_id] || params[:id]
      @reservation = Reservation.find(params[:id] ||= params[:reservation_id])
      @reservation.logs.create(message: 'Online donation successful.')
    end
    @driver = true if params[:driver] == true
    flash[:notice] = 'Thank you! Your donation is greatly appreciated and goes a long way towards supporting Scouting on Bainbridge Island.'
  end

  private
    def donation_params
      params.require(:donation).permit(:amount)
    end
    def set_reservation
      @reservation = Reservation.find(params[:id] ||= params[:reservation_id])
    end
end

app/views/donations/_form.html.haml
.row
  .col-lg-6
    %section
      %h3 Donate online
      %p Suggested donation is $25, but you can change this on the donation page.
      .text-center.mb-3
        = image_tag "credit_card.png", class: 'img-fluid', width: '250px'
      = form_tag [:reservation, :donations], local: true, data: { turbo:false } do
        .action.online
          = submit_tag 'Donate online', class: 'btn btn-primary btn-lg', id: 'button-donate-online'


  .col-lg-6
    %section
      %h3 Donate at pick-up
      %p Place your donation in an envelope and attach it to your tree before 8am on Jan 2023. Make checks payable to BSA Troop 1564 & 1804.
      = form_tag reservation_cash_or_check_path(reservation_id: @reservation.id), local: true, data: { turbo:false } do
        .action.pickup
          = submit_tag "Donate at pick-up", class: 'btn btn-primary btn-lg', id: 'button-donate-at-pickup'


%section
  .row
    .col-lg-12.thinking-about-it

      = form_tag reservation_no_donation_path(reservation_id: @reservation.id), local: true, data: { turbo:false } do
        .action.no-donation
          = submit_tag "No donation", class: 'btn btn-primary btn', id: 'button-donate-thinking'

app/views/donations/_stripe_js.html.erb
<script type="text/javascript">
  // Create an instance of the Stripe object with your publishable API key
  var stripe = Stripe("<%= ENV['STRIPE_PUBLISHABLE_KEY'] || Rails.application.credentials.stripe[:publishable_key] %>");
  var checkoutButton = document.getElementById("checkout-button");

  checkoutButton.addEventListener("click", function () {
    fetch("/charges", {
      method: "POST",
    })
      .then(function (response) {
        return response.json();
      })
      .then(function (session) {
        return stripe.redirectToCheckout({ sessionId: session.id });
      })
      .then(function (result) {
        // If redirectToCheckout fails due to a browser or network
        // error, you should display the localized error message to your
        // customer using error.message.
        if (result.error) {
          alert(result.error.message);
        }
      })
      .catch(function (error) {
        console.error("Error:", error);
      });
  });
</script>

app/views/donations/cash_or_check.html.haml
%h2.mt-3 Thank you! You can leave your cash or check donation with the tree.

app/views/donations/create_js.html.erb
var stripe = Stripe("<%= Rails.application.credentials.stripe.development.publishable_key %>")

stripe.redirectToCheckout({
    sessionId: '<%= @session.id %>'
}).then(function (result) {
    console.log(result.error_message)
});

app/views/donations/new.html.haml
#donation.container
  .row
    .col-lg-12
      %h1.donation.text-center.mb-3 Please consider a donation


  .row
    .col-lg-10.offset-lg-1
      %p
        Our service is free, but your donation provides opportunities for Scouts in Troop 1564 for boys, and Troop 1804 for girls, to go to camp and other outdoor adventures, with training in valuable lifelong skills.
        / %li We accept online donations (credit, debit, Apple and Google Pay) or donations at pick-up (cash or check)

  .row
    .col-lg-12.text-center.mb-2
      = image_tag "bsa-logo.png", width: '100px'

  .row
    .col-lg-12

      .positive-push Clicking a donation option will complete the registration process


  = render 'form'


  .row
    .col-lg-12
      %section
        #view-reservation= link_to "View reservation", reservation_path(@reservation)

app/views/donations/success.html.haml
.row.mt-5.mb-5
  .col-lg-12

    .important-message.info
      A receipt for your donation will be emailed to you.


- if params[:driver] == 'true'
  .row
    .col-lg-12.text-center
      = link_to driver_root_path do
        %i.bi.bi-arrow-left 
        Driver