config/routes.rb
Rails.application.routes.draw do
  match "(*any)",
    to: redirect(subdomain: ""),
    via: :all,
    constraints: { subdomain: "www" } unless Rails.env.test?\

  root 'home#index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get '/about' => 'home#about', as: 'about'
  get '/questions' => 'home#questions', as: 'questions'
  get '/search' => 'reservations#search', as: 'reservation_lookup'
  post '/search' => 'reservations#search'

  get '/donation' => 'donations#donation_without_reservation', as: 'donation_without_reservation'
  get '/thank-you-for-your-donation' => 'donations#success', as: 'success'

  get '/software' => 'home#software', as: 'software'

  post 'messages/reply' => 'messages#reply'

  get '/tree-program', to: redirect('/about') # this redirect old web links to this site

  get '/sitemap.xml', to: 'sitemap#index', as: 'sitemap', :defaults => {:format => 'xml'}

  resources :reservations, except: [:index] do
    get 'address-verification', as: 'address_verification'

    resources :donations, only: %i[ new create ]
    post 'cash-or-check' => 'donations#cash_or_check', as: 'cash_or_check'
    post 'no-donation' => 'donations#no_donation', as: 'no_donation'
    get 'donations/success' => 'donations#success', as: 'success'
    get 'donations/cancel' => 'donations#cancel', as: 'cancel'
    get 'confirmed' => 'reservations#confirmed', as: 'confirmed'


    post 'submit-reservation' => 'reservations#submit_confirmed_reservation', as: 'submit'
    get 'unsubscribe' => 'reservations#unsubscribe', as: 'unsubscribe'
    get 'resubscribe' => 'reservations#resubscribe', as: 'resubscribe'
  end

  post 'stripe-webhook' => "donations#stripe_webhook"

  namespace :driver do
    root 'zones#index'
    get 'instructions' => 'routes#instructions', as: 'instructions'
    get 'contact' => 'contact#index', as: 'contacts'
    get 'reservations/map' => 'reservations#map', as: 'reservations_map'
    get 'search' => 'reservations#search', as: 'search'
    resources :reservations, only: %i( update show ) do
      get 'map' => 'reservations#map', as: 'map'
    end
    resources :routes, only: %i( show index )
    resources :drivers, only: %i( index show )
    get '/routing' => 'zones#index', as: 'routing'
    get '/zones' => 'zones#index', as: 'zones'
  end

  namespace :admin do
    root 'admin#index'
    get 'operations/index' => 'operations#index', as: 'operations'
    patch 'operations/update'
    get '/routes/map-all' => 'routes#map_all', as: 'routes_map_all'
    resources :zones
    resources :drivers
    get 'logs' => 'logs#index', as: :logs
    resources :messages, only: [:index, :create, :destroy ]
    resources :marketing, only: [ :index ]

    resources :settings, only: [ :index, :edit, :update ]


    resources :users, only: [ :index, :update, :create, :destroy, :edit ]
    resources :driver_routes, only: [:create, :destroy]
    resources :points, only: [:create, :update, :destroy, :edit]
    delete 'reservations/archive-all' => 'reservations#post_event_archive', as: 'post_event_archive_reservations'
    delete 'reservations/destroy-all' => 'reservations#destroy_all', as: 'destroy_all_reservations'
    delete 'donations/destroy-all' => 'donations#destroy_all', as: 'destroy_all_donations'
    delete 'reservations/destroy-all-archived' => 'reservations#destroy_all_archived', as: 'destroy_all_archived_reservations'
    delete 'reservations/destroy-unconfirmed' => 'reservations#destroy_unconfirmed', as: 'destroy_unconfirmed_reservations'
    post 'reservations/destroy-reservations' => 'reservations#destroy_reservations', as: 'destroy_reservations'
    delete 'reservations/destroy-logs' => 'logs#destroy', as: 'destroy_all_logs'
    resources :donations do
      post 'send-donation-receipt' => 'donations#send_donation_receipt', as: 'send_donation_receipt'
    end
    resources :reservations, only: [ :index, :show, :edit, :update, :destroy, :archive ] do
      resources :donations
      get 'logs' => 'logs#reservation_index', as: 'logs'
      post 'process-route' => 'reservations#process_route', as: 'process_route'
      post 'process-geocode' => 'reservations#process_geocode', as: 'process_geocode'
      post 'archive' => 'reservations#archive', as: 'archive'
    end
    get '/routing' => 'zones#index', as: 'routing'
    get '/phone' => 'messages#show', as: 'phone'

    post '/marketing/send-email-1' => 'marketing#send_marketing_email_1', as: 'marketing_send_email_1'
    post '/marketing/send-email-2' => 'marketing#send_marketing_email_2', as: 'marketing_send_email_2'
    post '/send-pickup-reminders' => 'reservations#send_pickup_reminders', as: 'send_pickup_reminders'
    post '/marketing/reset-sent-campaigns' => 'marketing#reset_sent_campaigns', as: 'marketing_reset_sent_campaigns'
    get '/analytics' => 'analytics#index', as: 'analytics'

    post 'process-all-routes' => 'reservations#process_all_routes', as: 'process_all_routes'
    get 'map' => 'reservations#map', as: 'map'
    resources :routes, except: [ :index, :show ] do
      get 'map' => 'routes#map', as: 'map'
    end
    get 'search' => 'reservations#search', as: 'search'
    post 'res-upload' => 'reservations#upload', as: 'upload'
  end


  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match "/422", to: "errors#unprocessable_entity", via: :all
end

app/models/setting.rb
# Application and event day defaults, and hosting organization information is stored in the first record of this model.
class Setting < ApplicationRecord
  attribute :contact_name, :string, default: 'John Doe'
  attribute :contact_email, :string, default: 'john@example.com'
  attribute :contact_phone, :string, default: '206-555-1212'
  attribute :on_day_of_pickup_instructions, :string, default: 'Pickup day instructions...'
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < Admin::AdminController

  def index
    @setting = helpers.setting
  end

  def edit
  end

  def update
    if current_user.editor? || current_user.administrator?
      if helpers.setting.update(setting_params)
        redirect_to admin_settings_path
      else
        render :edit, status: :unprocessable_entity
      end
    else
      redirect_to admin_settings_path, notice: 'Unauthorized. Editor or Administrator access is required. ', status: :unauthorized
    end
  end

  private
    def setting_params
      params.require(:setting).permit(:site_description, :contact_name, :contact_email, :contact_phone, :description, :is_reservations_open, :is_reservations_editable, :is_emailing_enabled, :on_day_of_pickup_instructions, :driver_secret_key, :meta_site_name, :meta_title, :meta_description, :meta_image_filename, :facebook_page_id, :reservations_closed_message, :is_driver_site_enabled, :email_batch_quantity, :driver_instructions, :is_sms_enabled)
    end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: %i[ show edit update destroy ]

  # GET /settings or /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1 or /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings or /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to setting_url(@setting), notice: "Setting was successfully created." }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1 or /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to setting_url(@setting), notice: "Setting was successfully updated." }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1 or /settings/1.json
  def destroy
    @setting.destroy

    respond_to do |format|
      format.html { redirect_to settings_url, notice: "Setting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def setting_params
      params.require(:setting).permit(:organization_name, :contact_name, :contact_email, :contact_phone, :description, :pickup_date)
    end
end

app/views/admin/settings/_form.html.haml
= form_for setting, url: admin_setting_path(setting) do |f|
  - if setting.errors.any?
    #error_explanation
      %h2= "#{pluralize(setting.errors.count, "error")} prohibited this setting from being saved:"
      %ul
        - setting.errors.full_messages.each do |message|
          %li= message
  .mb-3
    = f.label :site_description, class: 'form-label'
    = f.text_area :site_description, class: 'form-control'
    .form-text.text-muted Shown as the META description in the website headers for SEO
  .mb-3
    = f.label :description, class: 'form-label'
    = f.text_area :description, class: 'form-control'
    .form-text.text-muted Shown on 'About' page
  .mb-3
    = f.label :on_day_of_pickup_instructions, class: 'form-label'
    = f.text_area :on_day_of_pickup_instructions, class: 'form-control'
    .form-text.text-muted Shown on 'About' page
  / .mb-3.form-check
  /   = f.label :is_reservations_open, class: 'form-check-label'
  /   = f.check_box :is_reservations_open, class: 'form-check-input'
  /   .form-text.text-muted This enables creating, editing and cancelling reservations
  / .mb-3.form-check
  /   = f.label :is_emailing_enabled, class: 'form-check-label'
  /   = f.check_box :is_emailing_enabled, class: 'form-check-input'
  .mb-3
    = f.label :reservations_closed_message, class: 'form-label'
    = f.text_area :reservations_closed_message, placeholder: 'Message to show if reservations are closed...', class: 'form-control'
  .mb-3
    = f.label :is_driver_site_enabled, class: 'form-label'
    = f.check_box :is_driver_site_enabled, class: 'form-check-input'
  .mb-3
    = f.label :contact_name, class: 'form-label'
    = f.text_field :contact_name, class: 'form-control'
    .form-text.text-muted Shown on the 'Contact' page
  .mb-3
    = f.label :contact_email, class: 'form-label'
    = f.email_field :contact_email, class: 'form-control'
    .form-text.text-muted Shown on the 'Contact' page
  .mb-3
    = f.label :contact_phone, class: 'form-label'
    = f.text_field :contact_phone, class: 'form-control'
    .form-text.text-muted Shown on the 'Contact' page
  .mb-3
    = f.label :driver_secret_key, class: 'form-label'
    = f.text_field :driver_secret_key, class: 'form-control'
    .form-text.text-muted If there is a secret key, access to the Driver application requires a key as a param '.../?key=[secret key]'. A change in the key hear will invalidate any prior key usage.
  .mb-3
    = f.label :email_batch_quantity, class: 'form-label'
    = f.text_field :email_batch_quantity, class: 'form-control'
    .form-text.text-muted Quantity of emails to send at a time
  .mb-3
    = f.label :meta_site_name, class: 'form-label'
    = f.text_field :meta_site_name, class: 'form-control'
  .mb-3
    = f.label :meta_title, class: 'form-label'
    = f.text_field :meta_title, class: 'form-control'
  .mb-3
    = f.label :meta_description, class: 'form-label'
    = f.text_field :meta_description, class: 'form-control'
  .mb-3
    = f.label :meta_image_filename, class: 'form-label'
    = f.text_field :meta_image_filename, class: 'form-control'
    .form-text.text-muted File name of file in 'assets/images/'
  .mb-3
    = f.label 'Facebook Page ID', class: 'form-label'
    = f.text_field :facebook_page_id, class: 'form-control'
  .mb-3
    = f.label :driver_instructions, class: 'form-label'
    .text-muted Markdown styling can be used.
    = f.text_area :driver_instructions, rows: 20, class: 'form-control'

  .actions
    = f.submit 'Save', class: 'btn btn-primary'


%hr.mb-4.mt-5

%h2 Data Upload

= form_tag admin_upload_path, multipart: true do
  = label_tag  "Upload CSV File"
  = file_field_tag :file, class: 'form-control-file', required: true
  = submit_tag 'Submit', class: 'btn btn-primary'

app/views/admin/settings/_menu.html.haml
%ul.nav.flex-column.sticky-top#side-settings-nav
  %li.nav-item
    = link_to 'Reservations', admin_settings_path(anchor: 'reservation-settings'), class: "nav-link"
  %li.nav-item
    = link_to 'Event details', admin_settings_path(anchor: 'details'),class: "nav-link"
  %li.nav-item
    = link_to 'Website', admin_settings_path(anchor: 'content'),class: "nav-link"
  %li.nav-item
    = link_to 'Mapping', admin_settings_path(anchor: 'mapping'),class: "nav-link"
  %li.nav-item
    = link_to 'Driver', admin_settings_path(anchor: 'driver'),class: "nav-link"
  %li.nav-item
    = link_to 'Contact', admin_settings_path(anchor: 'contact'),class: "nav-link"
  %li.nav-item
    = link_to 'Users', admin_users_path,class: "nav-link"
  %li.nav-item
    = link_to 'SEO', admin_settings_path(anchor: 'seo'),class: "nav-link"
  %li.nav-item
    = link_to 'Messaging', admin_settings_path(anchor: 'messaging'),class: "nav-link"
  %li.nav-item
    = link_to 'Operations', admin_operations_path,class: "nav-link"
  %li.nav-item
    = link_to 'Logs', admin_logs_path,class: "nav-link"

app/views/admin/settings/edit.html.haml
.container
  %h1 Settings

  .row
    .col-md-8
      = render 'form'

app/views/admin/settings/index.html.haml
.container#settings
  .row
    .col-lg-12
      %h1
        %i.bi.bi-gear-fill
        Settings

  .row
    .col-lg-12
      .admin-nav
        %nav
          %ul.nav.justify-content-end
            %li.nav-item
              = link_to edit_admin_setting_path(setting) do
                %i.bi.bi-pencil-fill.icon
                EDIT
  .row
    .col-lg-2
      = render 'menu'

    .col-lg-10
      .row
        .col-lg-10
          .section
            .row
              .col-lg-4
                %h3#reservation-settings Reservations
              .col-lg-8
                .table-responsive
                  %table.table.settings.table-borderless#stats-table
                    %tr
                      %th
                        Reservations
                      %td
                        - if setting.is_reservations_open
                          Open

                          = button_to "Close", admin_setting_path(setting, setting: {is_reservations_open: false}), method: :patch, class: 'btn btn-danger btn-sm', disabled: current_user.administrator? ? false : true
                        - else
                          Closed
                          = button_to "Open", admin_setting_path(setting, setting: {is_reservations_open: true}), method: :patch, class: 'btn btn-danger btn-sm', disabled: current_user.administrator? ? false : true

                    %tr
                      %th Reservations closed message
                      %td= setting.reservations_closed_message

      .row
        .col-lg-10
          .section
            .row
              .col-lg-4
                %h3#details Event details
              .col-lg-8
                .table-responsive
                  %table.table.settings
                    %tbody
                      %tr
                        %th
                          Pick-up date start/end time

                        %td
                          = nice_date_time(Time.parse(EVENT_DATE_AND_PICKUP_TIME))
                          %br
                          = nice_date_time(Time.parse(EVENT_DATE_AND_PICKUP_END_TIME))
                      %tr
                        %th Signup deadline
                        %td= nice_date_time_no_year(Time.parse(EVENT_SIGN_UP_DEADLINE))

      .row
        .col-lg-10
          .section
            .row
              .col-lg-4
                %h3#content Website
              .col-lg-8
                .table-responsive
                  %table.table.settings
                    %tbody
                      %tr
                        %th Site title
                        %td= SITE_TITLE
                      %tr
                        %th Site description
                        %td= setting.site_description
                      %tr
                        %th Organization name
                        %td= ORGANIZATION_NAME
                      %tr
                        %th Description
                        %td= setting.description
                      %tr
                        %th Day of pickup instructions
                        %td= setting.on_day_of_pickup_instructions

      .row
        .col-lg-10
          .section
            .row
              .col-lg-4
                %h3#mapping Mapping
              .col-lg-8
                .table-responsive
                  %table.table.settings
                    %tr
                      %th Lookup service
                      %td.text-end
                        = Geocoder.config[:lookup].to_s.humanize


      .row
        .col-lg-10
          .section
            .row
              .col-lg-4
                %h3#driver Driver
              .col-lg-8
                .table-responsive
                  %table.table.table-borderless.settings
                    %tbody
                      %tr
                        %th
                        %td= link_to "Drivers", admin_drivers_path
                      %tr 
                        %th Is Driver Site enabled?
                        %td
                          - if setting.is_driver_site_enabled?
                            = link_to admin_setting_path(setting, setting: { is_driver_site_enabled: false } ), method: :patch, data: { 'turbo-method': 'patch' } do 
                              %i.bi.bi-check2-square
                          - else
                            = link_to admin_setting_path(setting, setting: { is_driver_site_enabled: true } ), method: :patch, data: { 'turbo-method': 'patch' } do 
                              %i.bi.bi-square

                      %tr
                        %th Driver Secret Key
                        %td
                          - if setting.driver_secret_key.present?
                            = setting.driver_secret_key
                          - else
                            No key

                      %tr 
                        %th Instructions
                        %td= setting&.driver_instructions&.html_safe


      .row
        .col-lg-10
          .section
            .row
              .col-lg-4
                %h3#contact Contact
              .col-lg-8
                .table-responsive
                  %table.table.table-borderless.settings

                    %tbody

                      %tr
                        %th Contact name
                        %td= setting.contact_name
                      %tr
                        %th Contact email
                        %td= setting.contact_email
                      %tr
                        %th Contact phone
                        %td= setting.contact_phone
                      %tr
                        %th
                          Email delivery

                        %td
                          - if setting.is_emailing_enabled
                            Delivering
                            - if current_user.administrator?
                              = button_to "Stop", admin_setting_path(setting, setting: {is_emailing_enabled: false}), method: :patch, class: 'btn btn-danger btn-sm'
                          - else
                            Stopped
                            - if current_user.administrator?
                              = button_to "Start", admin_setting_path(setting, setting: {is_emailing_enabled: true}), method: :patch, class: 'btn btn-danger btn-sm'

                      %tr
                        %th
                          SMS from phone
                        %td 
                          = Rails.application.credentials.twilio.production.number

                      %tr
                        %th
                          Email batch size
                        %td
                          = setting.email_batch_quantity



      .row
        .col-lg-10
          .section
            .row
              .col-lg-4
                %h3#seo SEO
              .col-lg-8
                .table-responsive
                  %table.table.settings
                    %tr
                      %th Meta Title
                      %td.text-end
                        = setting.meta_title
                    %tr
                      %th Meta Site Name
                      %td.text-end
                        = setting.meta_site_name
                    %tr
                      %th Meta Description
                      %td.text-end
                        = setting.meta_description
                    %tr
                      %th Meta Image filename
                      %td.text-end
                        = setting.meta_image_filename
                    %tr
                      %th Facebook Page ID
                      %td.text-end
                        = setting.facebook_page_id


      .row
        .col-lg-10
          .section
            .row
              .col-lg-4
                %h3#messaging Messaging
              .col-lg-8
                %div.mb-5
                  - if setting.is_emailing_enabled
                    .row.mb-1
                      .col-lg-5
                        .fw-bold Email is delivering
                      .col-lg-4
                        - if current_user.administrator?
                          .text-end
                            = button_to "Stop", admin_setting_path(setting, setting: {is_emailing_enabled: false}, source: 'marketing'), method: :patch, class: 'btn btn-sm btn-danger'
                  - else
                    .row.mb-1
                      .col-lg-5
                        .fw-bold Email is stopped
                      .col-lg-4
                        - if current_user.administrator?
                          .text-end
                            = button_to "Start", admin_setting_path(setting, setting: {is_emailing_enabled: true}, source: 'marketing'), method: :patch, class: 'btn btn-sm btn-danger'


                  .row
                    %p * This controls all automated email sending, except for donation receipts.



                %div.mb-7
                  - if setting.is_sms_enabled
                    .row.mb-1
                      .col-lg-5
                        .fw-bold SMS is delivering
                      .col-lg-4
                        - if current_user.administrator?
                          .text-end
                            = button_to "Stop", admin_setting_path(setting, setting: {is_sms_enabled: false}, source: 'marketing'), method: :patch, class: 'btn btn-sm btn-danger'
                  - else
                    .row.mb-1
                      .col-lg-5
                        .fw-bold SMS sending stopped
                      .col-lg-4
                        - if current_user.administrator?
                          .text-end
                            = button_to "Start", admin_setting_path(setting, setting: {is_sms_enabled: true}, source: 'marketing'), method: :patch, class: 'btn btn-sm btn-danger'

                  .row
                    %p * This controls automated sending of SMS's. This does not stop manual sending.