config/routes.rb
Rails.application.routes.draw do
  match "(*any)",
    to: redirect(subdomain: ""),
    via: :all,
    constraints: { subdomain: "www" } unless Rails.env.test?\

  root 'home#index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get '/about' => 'home#about', as: 'about'
  get '/questions' => 'home#questions', as: 'questions'
  get '/search' => 'reservations#search', as: 'reservation_lookup'
  post '/search' => 'reservations#search'

  get '/donation' => 'donations#donation_without_reservation', as: 'donation_without_reservation'
  get '/thank-you-for-your-donation' => 'donations#success', as: 'success'

  get '/software' => 'home#software', as: 'software'

  post 'messages/reply' => 'messages#reply'

  get '/tree-program', to: redirect('/about') # this redirect old web links to this site

  get '/sitemap.xml', to: 'sitemap#index', as: 'sitemap', :defaults => {:format => 'xml'}

  resources :reservations, except: [:index] do
    get 'address-verification', as: 'address_verification'

    resources :donations, only: %i[ new create ]
    post 'cash-or-check' => 'donations#cash_or_check', as: 'cash_or_check'
    post 'no-donation' => 'donations#no_donation', as: 'no_donation'
    get 'donations/success' => 'donations#success', as: 'success'
    get 'donations/cancel' => 'donations#cancel', as: 'cancel'
    get 'confirmed' => 'reservations#confirmed', as: 'confirmed'


    post 'submit-reservation' => 'reservations#submit_confirmed_reservation', as: 'submit'
    get 'unsubscribe' => 'reservations#unsubscribe', as: 'unsubscribe'
    get 'resubscribe' => 'reservations#resubscribe', as: 'resubscribe'
  end

  post 'stripe-webhook' => "donations#stripe_webhook"

  namespace :driver do
    root 'zones#index'
    get 'instructions' => 'routes#instructions', as: 'instructions'
    get 'contact' => 'contact#index', as: 'contacts'
    get 'reservations/map' => 'reservations#map', as: 'reservations_map'
    get 'search' => 'reservations#search', as: 'search'
    resources :reservations, only: %i( update show ) do
      get 'map' => 'reservations#map', as: 'map'
    end
    resources :routes, only: %i( show index )
    resources :drivers, only: %i( index show )
    get '/routing' => 'zones#index', as: 'routing'
    get '/zones' => 'zones#index', as: 'zones'
  end

  namespace :admin do
    root 'admin#index'
    get 'operations/index' => 'operations#index', as: 'operations'
    patch 'operations/update'
    get '/routes/map-all' => 'routes#map_all', as: 'routes_map_all'
    resources :zones
    resources :drivers
    get 'logs' => 'logs#index', as: :logs
    resources :messages, only: [:index, :create, :destroy ]
    resources :marketing, only: [ :index ]

    resources :settings, only: [ :index, :edit, :update ]


    resources :users, only: [ :index, :update, :create, :destroy, :edit ]
    resources :driver_routes, only: [:create, :destroy]
    resources :points, only: [:create, :update, :destroy, :edit]
    delete 'reservations/archive-all' => 'reservations#post_event_archive', as: 'post_event_archive_reservations'
    delete 'reservations/destroy-all' => 'reservations#destroy_all', as: 'destroy_all_reservations'
    delete 'donations/destroy-all' => 'donations#destroy_all', as: 'destroy_all_donations'
    delete 'reservations/destroy-all-archived' => 'reservations#destroy_all_archived', as: 'destroy_all_archived_reservations'
    delete 'reservations/destroy-unconfirmed' => 'reservations#destroy_unconfirmed', as: 'destroy_unconfirmed_reservations'
    post 'reservations/destroy-reservations' => 'reservations#destroy_reservations', as: 'destroy_reservations'
    delete 'reservations/destroy-logs' => 'logs#destroy', as: 'destroy_all_logs'
    resources :donations do
      post 'send-donation-receipt' => 'donations#send_donation_receipt', as: 'send_donation_receipt'
    end
    resources :reservations, only: [ :index, :show, :edit, :update, :destroy, :archive ] do
      resources :donations
      get 'logs' => 'logs#reservation_index', as: 'logs'
      post 'process-route' => 'reservations#process_route', as: 'process_route'
      post 'process-geocode' => 'reservations#process_geocode', as: 'process_geocode'
      post 'archive' => 'reservations#archive', as: 'archive'
    end
    get '/routing' => 'zones#index', as: 'routing'
    get '/phone' => 'messages#show', as: 'phone'

    post '/marketing/send-email-1' => 'marketing#send_marketing_email_1', as: 'marketing_send_email_1'
    post '/marketing/send-email-2' => 'marketing#send_marketing_email_2', as: 'marketing_send_email_2'
    post '/send-pickup-reminders' => 'reservations#send_pickup_reminders', as: 'send_pickup_reminders'
    post '/marketing/reset-sent-campaigns' => 'marketing#reset_sent_campaigns', as: 'marketing_reset_sent_campaigns'
    get '/analytics' => 'analytics#index', as: 'analytics'

    post 'process-all-routes' => 'reservations#process_all_routes', as: 'process_all_routes'
    get 'map' => 'reservations#map', as: 'map'
    resources :routes, except: [ :index, :show ] do
      get 'map' => 'routes#map', as: 'map'
    end
    get 'search' => 'reservations#search', as: 'search'
    post 'res-upload' => 'reservations#upload', as: 'upload'
  end


  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match "/422", to: "errors#unprocessable_entity", via: :all
end

app/models/driver.rb
class Driver < ApplicationRecord
  has_many :driver_routes, dependent: :destroy
  has_many :routes, through: :driver_routes

  scope :unzoned, -> { where(zone_id: nil) }
  scope :leader, -> { where(is_leader: true) }

  validates :name, :phone, presence: true
end

app/controllers/admin/drivers_controller.rb
class Admin::DriversController < Admin::AdminController
  before_action :set_driver, only: %i[ show edit update destroy ]

  def index
    @drivers = Driver.order(:name)
  end

  def show
    @driver_route = @driver.driver_routes.new 
  end

  def new
    @driver = Driver.new
    @driver_route = @driver.driver_routes.new 
  end

  def edit
    @driver_route = @driver.driver_routes.new
  end

  def create
    @driver = Driver.new(driver_params)

    if current_user.editor? || current_user.administrator?
      respond_to do |format|
        if @driver.save
          format.html { redirect_to admin_drivers_url, notice: "Driver was successfully created." }
          format.json { render :show, status: :created, location: @driver }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @driver.errors, status: :unprocessable_entity }
        end
      end
    else
      render :new, status: :unauthorized
    end
  end

  def update
    if current_user.editor? || current_user.administrator?
      respond_to do |format|
        if @driver.update(driver_params)
          format.html { redirect_to admin_drivers_url, notice: "Driver was successfully updated." }
          format.json { render :show, status: :ok, location: @driver }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @driver.errors, status: :unprocessable_entity }
        end
      end
    else
      render :show, status: :unauthorized
    end
  end

  def destroy
    if current_user.editor? || current_user.administrator?
      @driver.destroy
      respond_to do |format|
        format.html { redirect_to admin_drivers_url, notice: "Driver was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      render :show, status: :unauthorized
    end
  end

  private
    def set_driver
      @driver = Driver.find(params[:id])
    end

    def driver_params
      params.require(:driver).permit(:name, :email, :phone, :is_leader)
    end
end

app/controllers/driver/contact_controller.rb
class Driver::ContactController < Driver::DriverController
  def index
    # @zone_leaders = Driver.leader.includes(:zone).order('zones.name')
    @zones = Zone.all
  end
end

app/controllers/driver/driver_controller.rb
class Driver::DriverController < ApplicationController
  before_action :is_driver_signed_in?

  def instructions
    @instructions = helpers.setting.driver_instructions
  end

  def is_driver_signed_in?
    unless driver_signed_in?
      redirect_to sign_in_path
    end
    true
  end
end

app/controllers/driver/drivers_controller.rb
class Driver::DriversController < Driver::DriverController
  def index
    @zones = Zone.all.includes(:drivers)
  end

  def show
    @driver = Driver.find(params[:id])
  end
end

app/controllers/driver/reservations_controller.rb
class Driver::ReservationsController < Driver::DriverController
  def show
    @reservation = Reservation.not_archived.find(params[:id])
  end

  def search
    if params[:search]
      @query = params[:search]
      @pagy, @reservations = pagy(Reservation.not_archived.where("name ILIKE ? OR street ILIKE ? OR email ILIKE ?", "%" + Reservation.sanitize_sql_like(params[:search]) + "%", "%" + Reservation.sanitize_sql_like(params[:search]) + "%", "%" + Reservation.sanitize_sql_like(params[:search]) + "%"))
    end
  end

  def map
    flash[:notice] = "Reservation status changes are NOT enabled." unless helpers.setting.is_driver_site_enabled?
    if params[:route_id]
      @route = Route.find(params[:route_id])
      if params[:archived]
        @reservations = Reservation.where.not(status: ['unconfirmed', 'cancelled']).where(route: @route ).geocoded.map{ |r| [ r.id.to_s, r.street.to_s, r.latitude.to_s.to_f, r.longitude.to_s.to_f, r.notes || "", r.status.humanize.capitalize, r.phone || "", r.donation_status || "", r.collected || "", r.collected_amount || "", r.name || "", r.route.name || "", r.route.zone.name || "", r.admin_notes || "" ] }
      else
        @reservations = Reservation.pending.where(route: @route ).geocoded.map{ |r| [ r.id.to_s, r.street.to_s, r.latitude.to_s.to_f, r.longitude.to_s.to_f, r.notes || "", r.status.humanize.capitalize, r.phone || "", r.donation_status || "", r.collected || "", r.collected_amount || "", r.name || "", r.route.name || "", r.route.zone.name || "", r.admin_notes || "" ] }
      end
    elsif params[:zone_id]
      @zone = Zone.find(params[:zone_id])
      if params[:archived]
        @reservations = @zone.reservations.where.not(status: ['unconfirmed', 'cancelled']).geocoded.map{ |r| [ r.id.to_s, r.street.to_s, r.latitude.to_s.to_f, r.longitude.to_s.to_f, r.notes || "", r.status.humanize.capitalize, r.phone || "", r.donation_status || "", r.collected || "", r.collected_amount || "", r.name || "", r.route.name || "", r.route.zone.name || "", r.admin_notes || "" ] }        
      else
        @reservations = @zone.reservations.pending.geocoded.map{ |r| [ r.id.to_s, r.street.to_s, r.latitude.to_s.to_f, r.longitude.to_s.to_f, r.notes || "", r.status.humanize.capitalize, r.phone || "", r.donation_status || "", r.collected || "", r.collected_amount || "", r.name || "", r.route.name || "", r.route.zone.name || "", r.admin_notes || "" ] }
      end
    elsif params[:reservation_id]
      @reservation = Reservation.find(params[:reservation_id])
      @reservations = [ @reservation.id.to_s, @reservation.street.to_s, @reservation.latitude.to_s.to_f, @reservation.longitude.to_s.to_f, @reservation.notes || "", @reservation.status.humanize.capitalize, @reservation.phone || "", @reservation.donation || "", @reservation.collected || "", @reservation.collected_amount || "", @reservation.name || "", @reservation.route.name || "", @reservation.route.zone.name || "", @reservation.admin_notes || "" ]
    else
      @reservations = Reservation.pending.geocoded.map{ |r| [ r.id.to_s, r.street.to_s, r.latitude.to_s.to_f, r.longitude.to_s.to_f, r.notes || "", r.status.humanize.capitalize, r.phone || "", r.donation_status || "", r.collected || "", r.collected_amount || "", r.name || "", r.route.name || "", r.route.zone.name || "", r.admin_notes || "" ] }
    end
  end

  def update
    @reservation = Reservation.find(params[:id])
    if helpers.setting.is_driver_site_enabled?
      if params[:status]
        case params[:status]
        when  'picked_up'
          @reservation.picked_up!
        when 'missing'
          @reservation.missing!
        when 'pending_pickup'
          @reservation.pending_pickup!
        end
      else
        @reservation.collected = 'cash' if params[:collected] == 'cash'
        @reservation.collected = 'check' if params[:collected] == 'check'
        @reservation.collected = 'door_hanger' if params[:collected] == 'door_hanger'
        @reservation.collected_amount = params[:collected_amount] if params[:collected_amount].present?
        @reservation.save
      end
      if params[:view]=='map'
        redirect_to driver_reservations_map_path(route_id: @reservation.route_id)
      else 
        redirect_to driver_route_path(@reservation.route)
      end
    else
      redirect_to driver_route_path(@reservation.route), status: 405
    end
  end
end

app/controllers/driver/routes_controller.rb
class Driver::RoutesController < Driver::DriverController
  def index
    @zones = Zone.includes(:routes).order(:name)

    respond_to do |format|
      format.html
      format.pdf do 
        render pdf: "TreeRecycle Routes Report #{ Time.now.strftime('%^b-%d %H-%M')}",
        template: "driver/routes/index",
        page_size: 'Letter',
        orientation: "Landscape"
      end
    end
  end

  def show
    @route = Route.find(params[:id])
    @drivers = @route.drivers
    @reservations = @route.reservations.pending
    flash[:notice] = "Reservation status changes are NOT enabled." unless helpers.setting.is_driver_site_enabled?
    respond_to do |format|
      format.html
      format.pdf do 
        render pdf: "TreeRecycle Route Report-#{@route.name}-#{ Time.now.strftime('%^b-%d %H-%M')}",
        template: "driver/routes/show",
        page_size: 'Letter',
        orientation: "Landscape"
      end
    end
  end
end

app/controllers/driver/zones_controller.rb
class Driver::ZonesController < Driver::DriverController
  def index
    @zones = Zone.includes(:routes).order(:name)
    @pending_pickups_count = Reservation.pending_pickup.routed.count
    @missing_count = Reservation.missing.count
    @picked_up_count = Reservation.picked_up.count
  end

end

app/views/driver/drivers/_drivers.html.haml
.row
  .col-lg-12
    %h1
      %i.bi.bi-truck-front-fill
      Drivers

    - if admin_view?
      %p
        = link_to admin_settings_path do
          %i.bi.bi-arrow-left
          Settings


- if signed_in? && (current_user.editor? || current_user.administrator?)
  .row
    .col-lg-12
      .admin-nav
        %nav
          %ul.nav.justify-content-end
            %li.nav-item
              = link_to new_admin_driver_path, class: 'nav-link' do
                %i.bi.bi-plus-lg
                Driver




- Zone.all.each do |zone|
  .row
    .col-lg-8.offset-lg-2
      .table-responsive
        %table.table.drivers-table
          %tbody
            %tr.top-section
              %td.route-zone.zone
                = zone.name
              %td
              %td
              %td
              - if signed_in? && (current_user.editor? || current_user.administrator?)
                %td

            - Driver.joins(driver_routes: [:route] ).where("routes.zone_id = ?",zone.id).uniq.each do |driver|

              %tr
                %th.name
                  - name = driver.name
                  - name += ' (Leader)' if driver.is_leader?
                  = name
                %td.routes= driver.routes.order(:name).map {|r| r.name }.join(", ")
                %td.phone
                  - if driver.phone.present?
                    = link_to "tel:#{driver.phone}", id: "driver-#{driver.id}-phone-link" do
                      = driver.phone
                %td.email= mail_to driver.email
                - if signed_in? && (current_user.editor? || current_user.administrator?)
                  %td.actions-1
                    = link_to admin_driver_path(driver), method: :delete, data: { "turbo-method": :delete }, id: "driver-#{driver.id}-destroy-link"  do
                      %i.bi.bi-trash-fill
                    = link_to edit_admin_driver_path(driver), id: "driver-#{driver.id}-edit-link" do
                      %i.bi.bi-pencil-fill           

- @drivers_unassigned = Driver.where.not(id: DriverRoute.all.map {|dr| dr.driver_id })
- if @drivers_unassigned.any?
  .row
    .col-lg-8.offset-lg-2
      .table-responsive
        %table.table.drivers-table
          %tbody
            %tr.top-section
              %td.zone No Routes Assigned
              %td
              %td 
              %td 
              - if signed_in? && (current_user.editor? || current_user.administrator?)
                %td
          - @drivers_unassigned.each do |driver|
            %tr
              %th.name= driver.name
              %td.routes
              %td.phone
                - if driver.phone.present?
                  = link_to "tel:#{driver.phone}", id: "driver-#{driver.id}-phone-link" do
                    = driver.phone
              %td.email= mail_to driver.email
              - if signed_in? && (current_user.editor? || current_user.administrator?)
                %td.actions-1
                  = link_to admin_driver_path(driver), method: :delete, data: { "turbo-method": :delete }, id: "driver-#{driver.id}-destroy-link"  do
                    %i.bi.bi-trash-fill
                  = link_to edit_admin_driver_path(driver), id: "driver-#{driver.id}-edit-link" do
                    %i.bi.bi-pencil-fill 

app/views/driver/drivers/index.html.haml
.container
  .row
    .col-lg-12
      %h1
        %i.bi.bi-truck-front-fill
        Drivers

  .row
    .col-lg-6.offset-lg-3
      .table-responsive
        %table.table#drivers-table
          %tbody
            - @zones.each do |zone|
              - next unless zone.drivers.any?
              %tr
                %td.route-zone.zone
                  = zone.name
                %td
                %td
              - zone.drivers.each do |driver|
                %tr
                  %th.name= link_to driver.name, driver_driver_path(driver)
                  %td.phone
                    - if driver.phone.present?
                      = link_to "tel:#{driver.phone}" do
                        = driver.phone
                  %td.email= mail_to driver.email

            - if Driver.unzoned.any?
              %tr
                %td.zone No Zone
                %td.data
                %td.data

              - Driver.unzoned.each do |driver|
                %tr
                  %th.name= link_to driver.name, driver_driver_path(driver)
                  %td.phone
                    - if driver.phone.present?
                      = link_to "tel:#{driver.phone}" do
                        = driver.phone
                  %td.email= mail_to driver.email

app/views/driver/drivers/show.html.haml
#driver-profile
  .row
    .col-md-3
    .col-md-6
      %h1
        %i.bi.bi-person-fill
        = @driver.name


  .row
    .col-md-3
    .col-md-6.text-middle
      - if @driver.phone.present?
        = link_to "tel:#{@driver.phone}" do
          = @driver.phone
          %i.bi.bi-telephone-fill
      %br
      = mail_to @driver.email if @driver.email
    